#!/bin/bash
echo " Write a BASH shell script to check that a number that is taken as input is divisible by 3 or not"
echo "Enter the number for check :: "
read ch
c=`expr $ch % 3`
if [ $c -eq 0 ]
then
echo " yes"
else
echo "no"
fi
